# Generated by Django 5.1.7 on 2026-01-23 21:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BillingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_type", models.CharField(max_length=50)),
                (
                    "rate_per_month",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StorageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("legacy_2018", "Legacy (2018)"),
                            ("onefs_2025", "OneFS (2025)"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "rate_per_tb_per_year",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per TB per year",
                        max_digits=10,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="BillingRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prorated_days", models.IntegerField(default=0)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "generation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_records",
                        to="billing.billingcycle",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_records",
                        to="accounts.project",
                    ),
                ),
                (
                    "rate_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.billingrate",
                    ),
                ),
                (
                    "sponsored_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_records",
                        to="accounts.sponsoreduser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorageAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "allocated_tb",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Storage allocated in TB",
                        max_digits=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_allocations",
                        to="accounts.project",
                    ),
                ),
                (
                    "storage_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.storagetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorageBillingRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prorated_days", models.IntegerField(default=0)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "generation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_billing_records",
                        to="billing.billingcycle",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_billing_records",
                        to="accounts.project",
                    ),
                ),
                (
                    "storage_allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_records",
                        to="billing.storageallocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpeedcodeBillingAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "billing_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speedcode_allocations",
                        to="billing.billingrecord",
                    ),
                ),
                (
                    "project_speedcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.projectspeedcode",
                    ),
                ),
                (
                    "storage_billing_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speedcode_allocations",
                        to="billing.storagebillingrecord",
                    ),
                ),
            ],
        ),
    ]
